export enum LanguageMapKey {
    Biography = 'biography',
    Cbx =  'cbx',
    Work1 = 'work1',
    Work2 = 'work2',
    Work3 = 'work3',
    Work4 = 'work4',
    Work5 = 'work5',
    Work6 = 'work6',
    Work7 = 'work7',
    Intern = 'intern',
    InternWork1 = 'internWork1',
    InternWork2 = 'internWork2',
    InternWork3 = 'internWork3',
    InternWork4 = 'internWork4',
    Activities1 = 'activities1',
    Activities2 = 'activities2',
    Competition1 = 'competition1',
    Competition2 = 'competition2',
    Major = 'major'
}